// <auto-generated />
using EntityFrameWorkCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InheritanceCodeByEntityFramWork.Migrations
{
    [DbContext(typeof(SamirContext))]
    [Migration("20251223143319_TPTInheritanceDataCreate")]
    partial class TPTInheritanceDataCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Employee", b =>
                {
                    b.HasBaseType("InheritanceCodeByEntityFramWork.Models.Person");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Student", b =>
                {
                    b.HasBaseType("InheritanceCodeByEntityFramWork.Models.Person");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Employee", b =>
                {
                    b.HasOne("InheritanceCodeByEntityFramWork.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("InheritanceCodeByEntityFramWork.Models.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Student", b =>
                {
                    b.HasOne("InheritanceCodeByEntityFramWork.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("InheritanceCodeByEntityFramWork.Models.Student", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
