// <auto-generated />
using EntityFrameWorkCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InheritanceCodeByEntityFramWork.Migrations
{
    [DbContext(typeof(SamirContext))]
    [Migration("20251223150013_TPCInheritanceDataCreate")]
    partial class TPCInheritanceDataCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("PersonSequence");

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [PersonSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("PersonId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Employee", b =>
                {
                    b.HasBaseType("InheritanceCodeByEntityFramWork.Models.Person");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InheritanceCodeByEntityFramWork.Models.Student", b =>
                {
                    b.HasBaseType("InheritanceCodeByEntityFramWork.Models.Person");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
